### ISSUE TITLE
Cannot invoke find with no arguments

### ISSUE THREAD

**Issue by ghost** [gitdoapp/SugarRecord#147]
I recently updated to Xcode 6.3 and since then I'm getting this error everywhere I'm using find(). Can anyone help me with this ?

variable data is of SugarRecordResults? type

![screen shot 2015-04-10 at 5 51 44 pm](https://cloud.githubusercontent.com/assets/7509102/7087561/52a63390-dfaa-11e4-9260-90afe2fb4b9c.png)

**Comment by dchavezlive** [comment]
At a glance I'm not sure what your problem is. Have you pulled the latest code? I seem to be able to use find successfully as can be seen and tested [here](https://github.com/dchavezlive/SugarRecord-Example) its built in Xcode 6.3. You can also post your example if you'd like more detailed help.

**Comment by AustinChou** [comment]
@dchavezlive I tried the demo and modified the model, then the App began to crash because of `unexpectedly found nil while unwrapping an Optional value`. I'm sure that something wrong with NSNumber to StringLiteralConvertible in Swift 1.2. And also, lib doesn't generate the correct NSPredicate. 
I think this issue should be reopened.

**Comment by sureshkw** [comment]
Hi @AustinChou I couldn't fix this issue. When I was testing this library, I just assumed it'll just be a version compatibility problem and moved on with core data.

**Comment by pepibumur** [comment]
Fixing in SugarRecord 2.0
